# Generated by Django 5.1 on 2024-08-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecocode', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('variation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fideid', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('white_games_count', models.IntegerField()),
                ('black_games_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('result', models.CharField(max_length=10)),
                ('white_elo', models.IntegerField()),
                ('black_elo', models.IntegerField()),
                ('number_of_moves', models.IntegerField()),
                ('pgn', models.CharField(max_length=1536)),
                ('site', models.CharField(max_length=100)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.opening')),
                ('black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black', to='games.player')),
                ('white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='games.player')),
            ],
        ),
    ]
